In [3]:
5

5

In [1]:
pip install -U ipykernel

Requirement already satisfied: ipykernel in c:\users\nalam\appdata\roaming\python\python313\site-packages (6.29.5)
Requirement already satisfied: comm>=0.1.1 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (1.8.11)
Requirement already satisfied: ipython>=7.23.1 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (8.31.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (0.1.7)
Requirement already satisfied: nest-asyncio in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (24.2)
Requirement already satisfied: psutil in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (6.1.1)
Requirement already satisfied: pyzmq>=24 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (26.2.0)
Requirement already satisfied: tornado>=6.1 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (2.18.0)
Requirement already satisfied: stack_data in c:\users\nalam\appdata\roaming\python\python313\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from jupyter-client>=6.1.12->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.3.6)
Requirement already satisfied: pywin32>=300 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (308)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\nalam\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.13)
Requirement already satisfied: six>=1.5 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\nalam\appdata\roaming\python\python313\site-packages (from stack_data->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

VARIABLES

In [6]:
x=100

In [7]:
x

100

In [1]:
y=20

In [2]:
y

20

In [3]:
100==100

True

In [4]:
100==300

False

In [5]:
True and False

False

using IF condition

In [10]:
if 70<80:
    print("result")

result

In [11]:
a=11
b=a+22
if b>a*4:
    print("test1")
print("test2")

test2

In [12]:
a=20
b=a+30
c=b+a
if c>a and a==c and c+b>a:
    print("test1")
    print("test2")
print("test3")
if (a+b+c)/2>b+a:
    print("test4")

test3

LARGEST NUMBER

In [16]:
a=100
b=500
if a>b:
    print(a)
if b>a:
    print(b)

500

In [20]:
a=100
b=50
c=150
if a>b and a>c:
    print(a)
if b>a and b>c:
    print(b)
if c>a and c>b:
    print(c)

150

EVEN OR ODD

In [27]:
a=11%10
b=5%10
c=9%10
d=10%5
print(a, b, c, d)

1 5 9 0

In [30]:
a=16
if a%2==0:
    print("even")
if a%2!=0:
    print("odd")

even

IF-ELSE

In [32]:
if 10>20:
    print(10)
else:
    print(20)

10

In [33]:
if 10>20:
    print("test1")

if 20>10:
    print("test2")
else:
    print("test3")

test2

IF-ELIF-ELSE:

In [34]:
if 10>20:
    print("test1")
if 20>10:
    print("test2")
elif 7>6:   #elif condition checks the above if condition if it false it will execute or else it will not execute
    print("test4")  
else:    #else executes when all the above conditions are false
    print("test5")

test2

In [35]:
if 7>5:
    print("test1")
if 60>10:
    print("test2")    
elif 70>20:
    print("test3")
elif 60>20:
    print("test4")
else:
    print("test5")

test1
test2

In [36]:
if 6>5:
    print("test1")
if 50>9:
    print("test2")
else:
    print("test3")
if 90>6:
    print("test4")
elif 80>5:
    print("test5")
elif 90>56:
    print("test6")
else:
    print("test7")

test1
test2
test4

In [2]:
a=10 
b=a*5 #50
c=a+b #60
if a>5:
    c=c-a #50
    if c+a>10:
        a=a*2 #20
        print(a)
    c=c-a #30
    print(c)

20
30

In [3]:
a=10 
b=a*5 #50
c=a+b #60
if a>5:
    c=c-a #50
    if c+a>10:
        a=a*2 #20
        print(a)
    elif c-a<100: #doesnot print as if condition is true
        c=c-a #30
    else: # doesnot print as the if condition is laready is true
        print("Nothing")
    c=c-a #30
    print(c)

20
30

LOOPING

In [6]:
for i in range(5):
    print("Hello")

Hello
Hello
Hello
Hello
Hello

WHILE LOOP

In [ ]:
#WHILE LOOP SYNTAX

WHILE CONDITION:
    CODE
    CODE

In [2]:
n=1
while n<=10:
    print(n)
    n=n+1

1
2
3
4
5
6
7
8
9
10

ODD NUMBERS

In [4]:
n=1
while n<=50:
    print(n)
    n=n+2

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49

EVEN NUMBERS

In [5]:
n=2
while n<=20:
    print(n)
    n=n+2

2
4
6
8
10
12
14
16
18
20

FACTORS PRINTING

In [21]:
n=10
i=1
while i<n+1:
    if n%i==0:
        print(i)
    i=i+1

1
2
5
10

In [22]:
n=10
i=1
a=0
while i<n+1:
    if n%i==0:
        a=a+1
    i=i+1
print("count=",a)

count= 4

PRIME NUMBER

In [32]:
n=13
i=1
a=0
while i<n+1:
    if n%i==0:
        a=a+1
    i=i+1
print("count=",a) 
if a==2:
    print("it is prime number")
else:
    print("it is not prime number")

count= 2
it is prime number

FOR LOOP

In [ ]:
#SYNTAX
#FOR VAR IN RANGE(START, STOP, STEP)

In [2]:
for i in range(1,11,1):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [3]:
for i in range(2,11,2):
    print(i)

2
4
6
8
10

In [5]:
for i in range(1,20,2):
    print(i)

1
3
5
7
9
11
13
15
17
19

In [6]:
for i in range(10,0,-2):
    print(i)

10
8
6
4
2

In [11]:
sum=0
for i in range(2,51,2):
    sum=sum+i
print(sum)

650

In [12]:
count=0
for i in range(2,51,2):
    count=count+1
print(count)

25

PATTERNS

In [23]:
print(3*'+')

+++

In [14]:
#+
#++
#+++
#++++
#+++++

for i in range(1,6):
    print(i*'+')

+
++
+++
++++
+++++

In [19]:
#   *=>1 --(2*1)-1=>1
#  ***=>3 --(3*2)-1=>3
# *****=>4
#*******=>5
n=4
for i in range(1,n+1):
    print((n-i)*' ',((2*i)-1)*'*')

    *
   ***
  *****
 *******

In [20]:
n=10
for i in range(1,n+1):
    print((n-i)*' ',((2*i)-1)*'*')

          *
         ***
        *****
       *******
      *********
     ***********
    *************
   ***************
  *****************
 *******************

In [24]:
n=10
for i in range(n,0,-1):
    print((n-i)*' ',((2*i)-1)*'*')

 *******************
  *****************
   ***************
    *************
     ***********
      *********
       *******
        *****
         ***
          *

DATATYPES

In [28]:
x="Hello coder"
x.islower()
x.lower()

'hello coder'

In [30]:
#HLO
x[0:5:2]

'Hlo'

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.2.1-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\nalam\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.2.3-cp313-cp313-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 5.3 MB/s eta 0:00:02
   ------- -------------------------------- 2.1/11.5 MB 5.5 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/11.5 MB 5.5 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.5 MB 5.5 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.5 MB 5.6 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.5 MB 5.6 MB/s eta 0:00:01
   --------------------------- ------------ 7.9/11.5 MB 5.6 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.5 MB 5.5 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 5.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 5.0 MB/s eta 0:00:00
Downloading numpy-2.2.1-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 4.5 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/12.6 MB 4.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 4.8 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 4.6 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 4.4 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.6 MB 3.9 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.5 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.6 MB 3.2 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.6 MB 3.3 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.6 MB 3.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.6 MB 3.5 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 3.6 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 3.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.0 MB/s eta 0:00:00
Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.1 pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [7]:
df=pd.read_csv("crime.csv")

In [8]:
df.head(5)

   Year  Population  Murder  Rape  Robbery  Assault  Burglary  CarTheft
0  1965    18073000     836  2320    28182    27464    183443     58452
1  1966    18258000     882  2439    30098    29142    196127     64368
2  1967    18336000     996  2665    40202    31261    219157     83775
3  1968    18113000    1185  2527    59857    34946    250918    104877
4  1969    18321000    1324  2902    64754    36890    248477    115400

In [ ]:
#iloc-index position
#loc-index name

In [9]:
df.iloc[5:11:1]

    Year  Population  Murder  Rape  Robbery  Assault  Burglary  CarTheft
5   1970    18190740    1444  2875    81149    39145    267474    125674
6   1971    18391000    1823  3225    97682    42318    273704    127658
7   1972    18366000    2026  4199    86391    45926    239886    105081
8   1973    18265000    2040  4852    80795    47781    246246    112328
9   1974    18111000    1919  5240    86814    51454    271824    104095
10  1975    18120000    1996  5099    93499    54593    301996    116274

In [10]:
df=pd.read_csv("https://raw.githubusercontent.com/singhrau0/Big-Data-Preprocessing/refs/heads/main/youtubesample.csv ")

In [11]:
df.head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
0,m8Dqg8iz5Fo,18.09.05,MY INSTAGRAM FOLLOWERS PICK MY FULL FACE OF MA...,Sylvia Gani,26,2018-04-30T00:18:19.000Z,"i let my subscribers pick my makeup|""subscribe...",834848,35939,578,4121,https://i.ytimg.com/vi/m8Dqg8iz5Fo/default.jpg,False,False,False,SUBSCRIBE HERE: http://bit.ly/2g1cqFWHey S-Clu...,Howto & Style
1,2yCp-Dj5-7c,17.16.12,Does Tiffany Haddish Think NeNe Leakes Is Funn...,Watch What Happens Live with Andy Cohen,24,2017-12-11T04:29:53.000Z,"What What Happens live|""reality""|""interview""|""...",214016,1191,128,125,https://i.ytimg.com/vi/2yCp-Dj5-7c/default.jpg,False,False,False,Actress Tiffany Haddish says if she was nervou...,Entertainment
2,H00djJq68VE,17.27.12,Panettone (Italian Christmas Bread) - Food Wishes,Food Wishes,26,2017-12-23T00:07:02.000Z,"Panettone|""Italian""|""Christmas""|""Bread""|""holid...",283364,8274,332,1016,https://i.ytimg.com/vi/H00djJq68VE/default.jpg,False,False,False,"Learn how to make Panettone! Eaten as is, or t...",Howto & Style
3,oTObwUiXdYY,17.19.11,7.3 Magnitude Earthquake Along Iraq-Iran Borde...,TIME,25,2017-11-13T15:44:35.000Z,"7.3 magnitude earthquake|""earthquake iraq iran...",33761,149,45,222,https://i.ytimg.com/vi/oTObwUiXdYY/default.jpg,False,False,False,A powerful 7.3 magnitude earthquake near the I...,News & Politics
4,yvicqMrAHvQ,18.05.02,Turkish Airlines - 5 Senses with Dr. Oz,Turkish Airlines,19,2018-02-04T23:55:21.000Z,[none],936185,606,74,67,https://i.ytimg.com/vi/yvicqMrAHvQ/default.jpg,False,False,False,🌍✈️\nThere is a world of miracles. Get out the...,Travel & Events

In [12]:
df.iloc[5:11:1]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
5,qDAxDcjgn-8,17.18.11,Taylor Swift - Reputation ALBUM REVIEW,theneedledrop,10,2017-11-14T23:06:27.000Z,"album|""review""|""music""|""reviews""|""indie""|""unde...",274155,10765,750,2560,https://i.ytimg.com/vi/qDAxDcjgn-8/default.jpg,False,False,False,Listen: https://www.youtube.com/watch?v=3tmd-C...,Music
6,kton-qrKNLc,18.08.03,Meghan Trainor - No Excuses,MeghanTrainorVEVO,10,2018-03-01T13:00:05.000Z,"meghan trainor|""no excuses""|""no excuses offici...",8368595,261615,21536,19114,https://i.ytimg.com/vi/kton-qrKNLc/default.jpg,False,False,False,No Excuses available at Spotify: http://smartu...,Music
7,oRArmtMA9AI,18.15.03,Marshmello - FLY (Official Music Video),Marshmello,10,2018-03-09T05:01:14.000Z,"marshmello|""marshmello fly""|""fly""|""fly marshme...",7619961,298787,8484,35970,https://i.ytimg.com/vi/oRArmtMA9AI/default.jpg,False,False,False,Marshmello - Fly (ft. Leah Culver) http://smar...,Music
8,84p7f-Rh-RY,17.21.12,Kate Winslet On Working With Woody Allen | Los...,Los Angeles Times,25,2017-12-16T23:19:59.000Z,"Los Angeles Times|""LA Times""|""L. A. Times""|""Ka...",68755,129,416,170,https://i.ytimg.com/vi/84p7f-Rh-RY/default.jpg,False,False,False,It was a mixture of fear and excitement. Kate ...,News & Politics
9,Biex1XR_mpo,18.24.03,50 Mums | 50 Kids | 1 Extra Chromosome,Wouldn't Change a Thing,22,2018-03-12T09:45:51.000Z,"downs syndrome|""down syndrome""|""wouldn't chang...",3154213,49108,380,2202,https://i.ytimg.com/vi/Biex1XR_mpo/default.jpg,False,False,False,A carpool karaoke lip sync video in support of...,People & Blogs
10,RQm0nKoODo4,18.13.03,Take On Me in 20 Styles ft. Seth Everman,Ten Second Songs,10,2018-03-05T17:00:40.000Z,"katy perry|""juicy j""|""nirvana""|""queen""|""metall...",855201,65834,569,5397,https://i.ytimg.com/vi/RQm0nKoODo4/default.jpg,False,False,False,Watch the Allstar video I did with Seth ► http...,Music

In [13]:
df.loc[1744:4925:2]

Empty DataFrame
Columns: [video_id, trending_date, title, channel_title, category_id, publish_time, tags, views, likes, dislikes, comment_count, thumbnail_link, comments_disabled, ratings_disabled, video_error_or_removed, description, Genre]
Index: []

In [14]:
df.iloc[5:]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
5,qDAxDcjgn-8,17.18.11,Taylor Swift - Reputation ALBUM REVIEW,theneedledrop,10,2017-11-14T23:06:27.000Z,"album|""review""|""music""|""reviews""|""indie""|""unde...",274155,10765,750,2560,https://i.ytimg.com/vi/qDAxDcjgn-8/default.jpg,False,False,False,Listen: https://www.youtube.com/watch?v=3tmd-C...,Music
6,kton-qrKNLc,18.08.03,Meghan Trainor - No Excuses,MeghanTrainorVEVO,10,2018-03-01T13:00:05.000Z,"meghan trainor|""no excuses""|""no excuses offici...",8368595,261615,21536,19114,https://i.ytimg.com/vi/kton-qrKNLc/default.jpg,False,False,False,No Excuses available at Spotify: http://smartu...,Music
7,oRArmtMA9AI,18.15.03,Marshmello - FLY (Official Music Video),Marshmello,10,2018-03-09T05:01:14.000Z,"marshmello|""marshmello fly""|""fly""|""fly marshme...",7619961,298787,8484,35970,https://i.ytimg.com/vi/oRArmtMA9AI/default.jpg,False,False,False,Marshmello - Fly (ft. Leah Culver) http://smar...,Music
8,84p7f-Rh-RY,17.21.12,Kate Winslet On Working With Woody Allen | Los...,Los Angeles Times,25,2017-12-16T23:19:59.000Z,"Los Angeles Times|""LA Times""|""L. A. Times""|""Ka...",68755,129,416,170,https://i.ytimg.com/vi/84p7f-Rh-RY/default.jpg,False,False,False,It was a mixture of fear and excitement. Kate ...,News & Politics
9,Biex1XR_mpo,18.24.03,50 Mums | 50 Kids | 1 Extra Chromosome,Wouldn't Change a Thing,22,2018-03-12T09:45:51.000Z,"downs syndrome|""down syndrome""|""wouldn't chang...",3154213,49108,380,2202,https://i.ytimg.com/vi/Biex1XR_mpo/default.jpg,False,False,False,A carpool karaoke lip sync video in support of...,People & Blogs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,bqFjyo7I8fY,18.01.03,Red Velvet 레드벨벳 '봐 (Look)' Dance Practice,SMTOWN,10,2018-02-22T03:00:00.000Z,"Red Velvet|""레드벨벳""|""Bad Boy""|""The Perfect Red V...",2696501,159805,1976,12116,https://i.ytimg.com/vi/bqFjyo7I8fY/default.jpg,False,False,False,"Listen and download on iTunes & Apple Music, S...",Music
4996,K0u_kAWLJOA,18.25.01,God of War – Story Trailer | PS4,PlayStation,20,2018-01-23T16:00:02.000Z,"God of War|""Kratos""|""Atreus""|""E3 2017""|""E3""|""G...",1727422,83372,1107,10657,https://i.ytimg.com/vi/K0u_kAWLJOA/default.jpg,False,False,False,https://www.playstation.com/en-us/games/god-of...,Gaming
4997,XGd1dq1BatM,18.19.03,"Halsey - Alone (Audio) ft. Big Sean, Stefflon Don",HalseyVEVO,10,2018-03-15T22:00:01.000Z,"Halsey|""Alone""|""Big Sean""|""Stefflon Don""|""remi...",1176625,66964,1133,3076,https://i.ytimg.com/vi/XGd1dq1BatM/default.jpg,False,False,False,Alone available now: http://www.iamhalsey.com/...,Music
4998,vGTTSdrV37U,18.04.04,Camila Cabello WINS Favorite Breakout Artist 🎤...,Nickelodeon,24,2018-03-25T01:22:15.000Z,"Kids’ Choice Awards|""2018""|""music""|""video game...",724593,13113,807,1909,https://i.ytimg.com/vi/vGTTSdrV37U/default.jpg,False,False,False,The future is YOURS! \n\nSinger-songwriter Cam...,Entertainment
4999,DkeiKbqa02g,18.22.05,"Calvin Harris, Dua Lipa - One Kiss (Official V...",CalvinHarrisVEVO,10,2018-05-02T23:01:00.000Z,"calvin harris|""calvin harris one kiss""|""calvin...",62800938,781317,34495,24760,https://i.ytimg.com/vi/DkeiKbqa02g/default.jpg,False,False,False,Calvin Harris & Dua Lipa – One Kiss (Official ...,Music

In [15]:
df.loc[1744:4925:2]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
1744,0qpE8IHz3go,17.08.12,YOUTUBERS REACT TO THEIR OLD YOUTUBE CHANNEL P...,FBE,24,2017-11-30T22:00:00.000Z,"Reactception|""Old Channels""|""React to Themselv...",1152361,34441,949,3048,https://i.ytimg.com/vi/0qpE8IHz3go/default.jpg,False,False,False,CLICK TO SUBSCRIBE TO THE YOUTUBERS IN THIS EP...,Entertainment
1746,E5yFcdPAGv0,18.13.06,Gorillaz - Humility (Official Video),Gorillaz,10,2018-05-31T15:57:04.000Z,"humility|""Gorillaz Humanz""|""the now now""|""geor...",24280015,903304,29801,77951,https://i.ytimg.com/vi/E5yFcdPAGv0/default.jpg,False,False,False,‘Humility' feat. George Benson is taken from t...,Music
1748,9PhM-zCmTFs,17.18.11,DIY - Simon's Cat | NEW BLACK & WHITE!,Simon's Cat,15,2017-11-16T15:03:23.000Z,"diy|""electric drill""|""cats""|""cartoon""|""simons ...",336907,18768,177,603,https://i.ytimg.com/vi/9PhM-zCmTFs/default.jpg,False,False,False,'A curious cat helps his owner with home impro...,Pets & Animals
1750,WMs3NOW1TDs,18.11.03,World's Biggest Jelly in Slow Motion,The Slow Mo Guys,22,2018-03-07T17:00:02.000Z,"Super Slow Show|""Slow Motion""|""4K""|""Explosion""...",1791377,49182,2335,4185,https://i.ytimg.com/vi/WMs3NOW1TDs/default.jpg,False,False,False,"Dan really throws himself into this footage, a...",People & Blogs
1752,ulCdoCfw-bY,18.28.04,The Black Hole Bomb and Black Hole Civilizations,Kurzgesagt – In a Nutshell,27,2018-04-22T12:02:17.000Z,"black hole|""supermassive black hole""|""dyson sp...",3039618,167927,1645,11754,https://i.ytimg.com/vi/ulCdoCfw-bY/default.jpg,False,False,False,To support Kurzgesagt and learn more about Bri...,Education
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4916,lCT0OaVqIQE,18.19.02,Jeffrey Tambor Fired From 'Transparent' Follow...,CBS Los Angeles,25,2018-02-16T02:26:02.000Z,"CBS 2 News Mid-day|""jeffrey tambor""|""sexual mi...",1319,3,15,4,https://i.ytimg.com/vi/lCT0OaVqIQE/default.jpg,False,False,False,Jeffrey Tambor's firing comes after a transgen...,News & Politics
4918,qT0mpVcH3ZU,18.09.01,"New Year, New Me | Rudy Mancuso & Stephen Curry",Rudy Mancuso,23,2018-01-04T19:50:16.000Z,"Brita|""brita stream""|""brita filter""|""water fil...",2846237,153693,2910,6464,https://i.ytimg.com/vi/qT0mpVcH3ZU/default.jpg,False,False,False,Thank you Stephen Curry for bringing in the Ne...,Comedy
4920,f9psILoYmCc,17.03.12,Freeze! NZ Police’s most entertaining recruitm...,NZPoliceRecruitment,25,2017-11-26T04:00:04.000Z,[none],965328,20934,699,64,https://i.ytimg.com/vi/f9psILoYmCc/default.jpg,False,False,False,"With over 70 real cops, the police band, polic...",News & Politics
4922,Oyq8Di01nN8,18.23.02,Can Sound Exist In a Vacuum Chamber?,The King of Random,27,2018-02-18T15:00:02.000Z,"speaker|""vacuum""|""chamber""|""vacuum chamber""|""n...",1066682,16327,1669,3241,https://i.ytimg.com/vi/Oyq8Di01nN8/default.jpg,False,False,False,In today's video we're using a bluetooth speak...,Education
4924,-C_rvt0SwLE,18.27.02,Imagine Dragons - Next To Me (Audio),ImagineDragonsVEVO,10,2018-02-21T17:00:00.000Z,"Imagine|""Dragons""|""Next""|""To""|""Me""|""KIDinaKORN...",9192678,362913,5764,19633,https://i.ytimg.com/vi/-C_rvt0SwLE/default.jpg,False,False,False,"Listen to Next To Me, out now: http://smarturl...",Music

In [17]:
df[df['channel_title']=='TIME']

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
3,oTObwUiXdYY,17.19.11,7.3 Magnitude Earthquake Along Iraq-Iran Borde...,TIME,25,2017-11-13T15:44:35.000Z,"7.3 magnitude earthquake|""earthquake iraq iran...",33761,149,45,222,https://i.ytimg.com/vi/oTObwUiXdYY/default.jpg,False,False,False,A powerful 7.3 magnitude earthquake near the I...,News & Politics
156,ESKmRiLjNpg,18.19.05,An Expert's Take On The Symbolism In Childish ...,TIME,25,2018-05-08T17:52:37.000Z,"donald glover|""snl""|""gun violence""|""this is am...",2208947,21887,7304,3517,https://i.ytimg.com/vi/ESKmRiLjNpg/default.jpg,False,False,False,Donald Glover released a new song and music vi...,News & Politics
302,NuZJQ-YS7_w,18.24.02,Former Trump Adviser Rick Gates Is About To Pl...,TIME,25,2018-02-23T18:36:24.000Z,"rick gates robert mueller|""rick gates trump""|""...",11689,132,112,147,https://i.ytimg.com/vi/NuZJQ-YS7_w/default.jpg,False,False,False,A former top adviser to the Trump campaign is ...,News & Politics
1385,BR7AnZ3S8u8,17.17.12,A Federal Judge In Philadelphia Blocks Preside...,TIME,25,2017-12-15T22:36:20.000Z,"federal judge|""trump birth control""|""birth con...",11698,108,88,251,https://i.ytimg.com/vi/BR7AnZ3S8u8/default.jpg,False,False,False,A federal judge in Philadelphia on Friday orde...,News & Politics
1590,0XARMt12oFk,17.28.12,Multiple Casualties And Injuries Reported As A...,TIME,25,2017-12-18T18:26:52.000Z,"amtrak train derails|""amtrak""|""washington""|""tr...",1339943,6223,1708,3828,https://i.ytimg.com/vi/0XARMt12oFk/default.jpg,False,False,False,An Amtrak train making the first-ever run alon...,News & Politics
2866,zsbT6NMUrSk,18.30.01,Judge Aquilina Delivers Powerful Statement Bef...,TIME,25,2018-01-24T20:24:08.000Z,"larry nassar sentencing judge|""larry nassar ju...",151965,1241,99,570,https://i.ytimg.com/vi/zsbT6NMUrSk/default.jpg,False,False,False,"Before issuing Larry Nassar's sentence, Judge ...",News & Politics
3225,cgYHbIEZWW8,18.22.02,FBI Admits It Failed To Investigate Tip About ...,TIME,25,2018-02-16T18:45:03.000Z,"fbi investigation florida shooting|""fbi florid...",386849,2425,1009,2657,https://i.ytimg.com/vi/cgYHbIEZWW8/default.jpg,False,False,False,The FBI admitted Friday that it received a det...,News & Politics
4121,ESKmRiLjNpg,18.15.05,An Expert's Take On The Symbolism In Childish ...,TIME,25,2018-05-08T17:52:37.000Z,"donald glover|""snl""|""gun violence""|""this is am...",2097374,21376,7082,3456,https://i.ytimg.com/vi/ESKmRiLjNpg/default.jpg,False,False,False,Donald Glover released a new song and music vi...,News & Politics

In [19]:
df[df['views']>500000]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
0,m8Dqg8iz5Fo,18.09.05,MY INSTAGRAM FOLLOWERS PICK MY FULL FACE OF MA...,Sylvia Gani,26,2018-04-30T00:18:19.000Z,"i let my subscribers pick my makeup|""subscribe...",834848,35939,578,4121,https://i.ytimg.com/vi/m8Dqg8iz5Fo/default.jpg,False,False,False,SUBSCRIBE HERE: http://bit.ly/2g1cqFWHey S-Clu...,Howto & Style
4,yvicqMrAHvQ,18.05.02,Turkish Airlines - 5 Senses with Dr. Oz,Turkish Airlines,19,2018-02-04T23:55:21.000Z,[none],936185,606,74,67,https://i.ytimg.com/vi/yvicqMrAHvQ/default.jpg,False,False,False,🌍✈️\nThere is a world of miracles. Get out the...,Travel & Events
6,kton-qrKNLc,18.08.03,Meghan Trainor - No Excuses,MeghanTrainorVEVO,10,2018-03-01T13:00:05.000Z,"meghan trainor|""no excuses""|""no excuses offici...",8368595,261615,21536,19114,https://i.ytimg.com/vi/kton-qrKNLc/default.jpg,False,False,False,No Excuses available at Spotify: http://smartu...,Music
7,oRArmtMA9AI,18.15.03,Marshmello - FLY (Official Music Video),Marshmello,10,2018-03-09T05:01:14.000Z,"marshmello|""marshmello fly""|""fly""|""fly marshme...",7619961,298787,8484,35970,https://i.ytimg.com/vi/oRArmtMA9AI/default.jpg,False,False,False,Marshmello - Fly (ft. Leah Culver) http://smar...,Music
9,Biex1XR_mpo,18.24.03,50 Mums | 50 Kids | 1 Extra Chromosome,Wouldn't Change a Thing,22,2018-03-12T09:45:51.000Z,"downs syndrome|""down syndrome""|""wouldn't chang...",3154213,49108,380,2202,https://i.ytimg.com/vi/Biex1XR_mpo/default.jpg,False,False,False,A carpool karaoke lip sync video in support of...,People & Blogs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,bqFjyo7I8fY,18.01.03,Red Velvet 레드벨벳 '봐 (Look)' Dance Practice,SMTOWN,10,2018-02-22T03:00:00.000Z,"Red Velvet|""레드벨벳""|""Bad Boy""|""The Perfect Red V...",2696501,159805,1976,12116,https://i.ytimg.com/vi/bqFjyo7I8fY/default.jpg,False,False,False,"Listen and download on iTunes & Apple Music, S...",Music
4996,K0u_kAWLJOA,18.25.01,God of War – Story Trailer | PS4,PlayStation,20,2018-01-23T16:00:02.000Z,"God of War|""Kratos""|""Atreus""|""E3 2017""|""E3""|""G...",1727422,83372,1107,10657,https://i.ytimg.com/vi/K0u_kAWLJOA/default.jpg,False,False,False,https://www.playstation.com/en-us/games/god-of...,Gaming
4997,XGd1dq1BatM,18.19.03,"Halsey - Alone (Audio) ft. Big Sean, Stefflon Don",HalseyVEVO,10,2018-03-15T22:00:01.000Z,"Halsey|""Alone""|""Big Sean""|""Stefflon Don""|""remi...",1176625,66964,1133,3076,https://i.ytimg.com/vi/XGd1dq1BatM/default.jpg,False,False,False,Alone available now: http://www.iamhalsey.com/...,Music
4998,vGTTSdrV37U,18.04.04,Camila Cabello WINS Favorite Breakout Artist 🎤...,Nickelodeon,24,2018-03-25T01:22:15.000Z,"Kids’ Choice Awards|""2018""|""music""|""video game...",724593,13113,807,1909,https://i.ytimg.com/vi/vGTTSdrV37U/default.jpg,False,False,False,The future is YOURS! \n\nSinger-songwriter Cam...,Entertainment
4999,DkeiKbqa02g,18.22.05,"Calvin Harris, Dua Lipa - One Kiss (Official V...",CalvinHarrisVEVO,10,2018-05-02T23:01:00.000Z,"calvin harris|""calvin harris one kiss""|""calvin...",62800938,781317,34495,24760,https://i.ytimg.com/vi/DkeiKbqa02g/default.jpg,False,False,False,Calvin Harris & Dua Lipa – One Kiss (Official ...,Music

In [25]:
df[(df['channel_title']=='TIME') & (df['comment_count']<1000)]

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,Genre
3,oTObwUiXdYY,17.19.11,7.3 Magnitude Earthquake Along Iraq-Iran Borde...,TIME,25,2017-11-13T15:44:35.000Z,"7.3 magnitude earthquake|""earthquake iraq iran...",33761,149,45,222,https://i.ytimg.com/vi/oTObwUiXdYY/default.jpg,False,False,False,A powerful 7.3 magnitude earthquake near the I...,News & Politics
302,NuZJQ-YS7_w,18.24.02,Former Trump Adviser Rick Gates Is About To Pl...,TIME,25,2018-02-23T18:36:24.000Z,"rick gates robert mueller|""rick gates trump""|""...",11689,132,112,147,https://i.ytimg.com/vi/NuZJQ-YS7_w/default.jpg,False,False,False,A former top adviser to the Trump campaign is ...,News & Politics
1385,BR7AnZ3S8u8,17.17.12,A Federal Judge In Philadelphia Blocks Preside...,TIME,25,2017-12-15T22:36:20.000Z,"federal judge|""trump birth control""|""birth con...",11698,108,88,251,https://i.ytimg.com/vi/BR7AnZ3S8u8/default.jpg,False,False,False,A federal judge in Philadelphia on Friday orde...,News & Politics
2866,zsbT6NMUrSk,18.30.01,Judge Aquilina Delivers Powerful Statement Bef...,TIME,25,2018-01-24T20:24:08.000Z,"larry nassar sentencing judge|""larry nassar ju...",151965,1241,99,570,https://i.ytimg.com/vi/zsbT6NMUrSk/default.jpg,False,False,False,"Before issuing Larry Nassar's sentence, Judge ...",News & Politics

In [ ]:
whose views is less than 1lakh and comment is less than 100

In [30]:
df[df['channel_title'] & (df['comment_count']<100)&(df['views']<100000)]

TypeError: unsupported operand type(s) for &: 'str' and 'bool'

In [ ]:
df[(df['comment_count']<100)&(df['views']<100000)]